export default {
    "start": [
        "thad",
        "thah",
        "then",
        "thur",
        "ther",
        "thul",
        "thei",
        "thaith",
        "thel",
        "svun",
        "yosh",
        "osh",
        "yo",
        "Yoth",
        "yael",
    ],
    "end": [
        "rael",
        "yael",
        "vael",
        "uel",
        "ren",
        "thad",
        "ael",
        "ven",
        "reth",
        "thulf",
        "osh",
        "mir",
        "dir",
        "hael"
    ]
}